### ISSUE TITLE
Add Hyper_L, Hyper_R and Mode_switch keys to the stdlib

### ISSUE THREAD

**Issue by yilkalargaw** [myfreeweb/evscript#16]
I had an xcape setup in which I use caps_lock and semicolon as hyper  keys and I can't refer to them as key functions. Can they be added to to the stdlib  to allow people who use the spacecadet modifiers?

**Comment by valpackett** [comment]
I'm not sure what you mean by "can't refer to them as key functions"??

**Comment by yilkalargaw** [comment]
I get an error when I say use any of the following 

```
xcape(mut should_lhyper, evt, KEY_LEFTHYPER(), [KEY_Semicolon()])
xcape(mut should_lhyper, evt, KEY_HyperL(), [KEY_Semicolon()])
```

**Comment by valpackett** [comment]
Ah. Well, there is no "LEFTHYPER" in [input-event-codes](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h), which is why we can't add them. As far as evdev is concerned, hyper does not exist. Hyper (and Super) are purely xkb (libxkbcommon) concepts, you can [tell xkb to interpret some random key that actually exists as Hyper](https://shapr.github.io/posts/2019-07-21-space-cadet.html) and use that key here. For example `KEY_F15` like in that article or something.

**Comment by yilkalargaw** [comment]
Thank you very much. I did as you suggested and it worked.
